"""Checkbox for employer preference category

Revision ID: 326495f21353
Revises: cc63a5fb7c00
Create Date: 2025-10-19 07:05:46.269477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326495f21353'
down_revision = 'cc63a5fb7c00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('interview_focus_resume_fit', sa.Boolean(), nullable=True))
    op.add_column('vacancies', sa.Column('interview_focus_hard_skills', sa.Boolean(), nullable=True))
    op.add_column('vacancies', sa.Column('interview_focus_soft_skills', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'interview_focus_soft_skills')
    op.drop_column('vacancies', 'interview_focus_hard_skills')
    op.drop_column('vacancies', 'interview_focus_resume_fit')
    # ### end Alembic commands ###
